name: 'action-jira-linker'
description: 'Add JIRA issue details to your GitHub pull request.'
author: 'thekevinbrown'
inputs:
  github-token:
    description: 'Token used to update PR description and add labels. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
  jira-user:
    description: 'JIRA username (email address) of the user that created the token. Can be passed in using {{ secrets.JIRA_USER }}'
    required: true
  jira-token:
    description: 'API Token used to access the JIRA REST API. Must have read access to your JIRA Projects & Issues.'
    required: true
  jira-base-url:
    description: 'The subdomain of JIRA cloud that you use to access it. Ex: "https://your-domain.atlassian.net"'
    required: true
  comment-header:
    description: 'A message that will be added to the top of the PR comment in markdown format. Default is "".'
    required: false
    default: ''
  comment-trailer:
    description: 'A message that will be added to the bottom of the PR comment in markdown format. Default is "".'
    required: false
    default: ''
  fail-on-error:
    description: 'Set this to true if you want action-jira-linker to fail the PR if it cannot find a JIRA issue. Default is false.'
    required: false
    default: false
  ignore-string:
    description: 'String that will be ignored when searching for JIRA keys'
    required: false
    default: ''
  force-update:
    description: 'Set this to true if you want action-jira-linker to add the comment for PRs that have not been recently opened at the risk of creating duplicate comments, this can be useful while testing the action integration.'
    required: false
    default: false
  update-body:
    description: 'Update the issue body with the comment instead of adding a comment'
    required: false
    default: false
  include-title:
    description: 'Add jira ticket summary to generated link'
    required: false
    default: false
  link-prefix:
    description: 'Text which is added before the jira ticket link'
    required: false
    default: 'JIRA Issue: '

runs:
  using: 'node20'
  main: 'lib/index.js'
branding:
  icon: 'check-square'
  color: 'blue'
